spring.threads.virtual.enabled=true
spring.task.execution.pool.core-size=50
spring.task.execution.pool.max-size=100
spring.task.execution.pool.queue-capacity=500
spring.task.execution.thread-name-prefix=NfAsync-

# Configuração do padrão de Retry do Resilience4j
resilience4j.retry.instances.integracoesPosVenda.max-attempts=3
resilience4j.retry.instances.integracoesPosVenda.wait-duration=1000
# Ativa o Backoff Exponencial (ex: tenta em 1s, depois 2s, depois 4s...)
resilience4j.retry.instances.integracoesPosVenda.enable-exponential-backoff=true
resilience4j.retry.instances.integracoesPosVenda.exponential-backoff-multiplier=2
# Ativa o Jitter (Variação aleatória para mitigar o efeito manada)
resilience4j.retry.instances.integracoesPosVenda.enable-randomized-wait=true
resilience4j.retry.instances.integracoesPosVenda.randomized-wait-factor=0.5

management.endpoints.web.exposure.include=health,info,prometheus

management.metrics.tags.application=gerador-nota-fiscal
management.endpoint.health.show-details=always